version: '3.8'
services:
  oznak-api:
    build: .
    command: uvicorn src.api.rest:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
