databases:
  database1:
    type: mysql
    host: 192.168.10.11
    port: 3306
    database: prod_database1
    table: measurements

  database2:
    type: mysql
    host: 192.168.10.12
    port: 3306
    database: prod_database2
    table: measurements

  database3:
    type: mssql
    host: 192.168.10.13
    port: 1433
    database: prod_database3
    table: main_data

  database4:
    type: mysql
    host: 192.168.10.14
    port: 3306
    database: prod_database4
    table: measurements

