databases:
  line1:
    type: mysql
    host: 192.168.10.11
    port: 3306
    database: prod_line1
    table: measurements

  line2:
    type: mysql
    host: 192.168.10.12
    port: 3306
    database: prod_line2
    table: measurements

  line3:
    type: mssql
    host: 192.168.10.13
    port: 1433
    database: prod_line3
    table: main_data

  line4:
    type: mysql
    host: 192.168.10.14
    port: 3306
    database: prod_line4
    table: measurements

